name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew
        # This is the key change 👇
        working-directory: ./AdsDisplayApp/

      - name: Build APK
        run: ./gradlew assembleDebug --no-daemon
        # This is the key change 👇
        working-directory: ./AdsDisplayApp/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          # This is also updated to find the APK
          path: AdsDisplayApp/app/build/outputs/apk/debug/app-debug.apk
          
