name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew
        # This is where the workflow is directed to the correct folder
        working-directory: ./adsdisplayapp/

      - name: Build APK
        run: ./gradlew assembleDebug --no-daemon
        # This is where the workflow runs the build command from your project's directory
        working-directory: ./adsdisplayapp/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          # The path to the artifact is also relative to the root of your repository
          path: adsdisplayapp/app/build/outputs/apk/debug/app-debug.apk
          
